### ISSUE TITLE
[Cryptofacilities] CryptoFacilitiesDigest - Java 11 code fails in Java 8 environment

### ISSUE THREAD

**Issue by sizmestiev** [knowm/XChange#4118] opened 2021-06-11 10:06 UTC
Seems like Java 11 code was introduced in CryptoFacilitiesDigest:
https://github.com/knowm/XChange/blob/e28c9b066768dbb2a4800d7b8a067b503d73ae4f/xchange-cryptofacilities/src/main/java/org/knowm/xchange/cryptofacilities/service/CryptoFacilitiesDigest.java#L52

https://github.com/knowm/XChange/commit/6ddd2e3bd568fbf64bb80dc8c39a5c5c17a80ad7#diff-6ec4afdd46cac2fa3bfee1282876504ced1c0c5fd6258a7fc778786568c4e8db

It fails in Java 8 env.

XChange v5.0.8

```
error: java.net.URLDecoder.decode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; 
java.lang.NoSuchMethodError: java.net.URLDecoder.decode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at org.knowm.xchange.cryptofacilities.service.CryptoFacilitiesDigest.digestParams(CryptoFacilitiesDigest.java:50)
	at si.mazi.rescu.Params.digestAll(Params.java:203)
	at si.mazi.rescu.RestInvocation.lambda$new$1(RestInvocation.java:93)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at si.mazi.rescu.RestInvocation.<init>(RestInvocation.java:93)
	at si.mazi.rescu.RestInvocation.create(RestInvocation.java:139)
	at si.mazi.rescu.RestInvocationHandler.createInvocation(RestInvocationHandler.java:182)
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:110)
	at com.sun.proxy.$Proxy15.accounts(unknown)
	at org.knowm.xchange.cryptofacilities.service.CryptoFacilitiesAccountServiceRaw.getCryptoFacilitiesAccounts(CryptoFacilitiesAccountServiceRaw.java:24)
```

@andre77

**Comment by walec51** [comment] 2021-06-11 10:25
we stopped supporting Java 8: https://github.com/knowm/XChange/issues/2945

**Comment by sizmestiev** [comment] 2021-06-11 10:29
From which library version?
Why pom.xml still has 1.8 compatibility?

https://github.com/knowm/XChange/blob/e28c9b066768dbb2a4800d7b8a067b503d73ae4f/pom.xml#L33
https://github.com/knowm/XChange/blob/e28c9b066768dbb2a4800d7b8a067b503d73ae4f/pom.xml#L464

**Comment by sizmestiev** [comment] 2021-06-11 10:36
> 
> 
> we stopped supporting Java 8: #2945

I can see only suggestions here, no definite decisions at all. Have I missed something?

**Comment by cymp** [comment] 2021-06-13 20:32
> we stopped supporting Java 8: #2945

Wait what? @timmolter could you confirm?

**Comment by walec51** [comment] 2021-06-13 21:28
this was @timmolter last comment before closing this issue: https://github.com/knowm/XChange/issues/2945#issuecomment-640188796

my only concern was Android support there

do you need Java 8 support because your building an app android?

**Comment by cymp** [comment] 2021-06-14 09:18
In my personal case I would prefer switching completely to J11, but the problem is, are we allowed to commit J11 non J8 complient code.

**Comment by timmolter** [comment] 2021-06-14 09:24
Because this library is used in Android, it needs to be Java 8 compatible. I recently ran into Android issues from a developer's point of view with noncompliant Java code, and it was a pain in the butt.

**Comment by sizmestiev** [comment] 2021-06-14 09:47
I use the library in a large enough setup (Linux) which is based on Java 8 and could not be switched to Java 11.

J11 code was introduced in 5.0.7. Just wondering - how the library was released (taking into account 1.8 compatibility checks https://github.com/knowm/XChange/issues/4118#issuecomment-859481748)?

**Comment by walec51** [comment] 2021-06-14 09:54
> Because this library is used in Android, it needs to be Java 8 compatible. I recently ran into Android issues from a developer's point of view with noncompliant Java code, and it was a pain in the butt.

if so then the Java 8 CI build must be restored - without it we wont detect which PRs use APIs that are from Java 9 and above

the Java versions mentioned in pom to not check for that

**Comment by timmolter** [comment] 2021-06-14 11:14
Yes, I must admit, it was never fully clarified one way or the other and always in a grey area. The way it works now is that Java 11 is used to compile it as Java 8 compatible. While even that can cause problems for Android in some edge cases, I think it's a good compromise. What do you think?

**Comment by walec51** [comment] 2021-06-14 11:48
As this issue illustrated at the moment we only ensure Java 8 bytecode compatibility - which means:
- you can import this library to a Java 8 project
- but it will always break in runtime when a method from Java 9 API or above is used and the underneath JRE does not support them

@timmolter as I understand your response Android despite requiring Java 8 bytecode provides many APIs from Java 9 an higher, yes?

If so then I'm sorry @sizmestiev but if your stuck with using Java 8 on the server then you must be already used to running old versions of unsupported libraries and components on it. There are many option available to you to remedy your situation like for example using containers and microservices if you want to use the latest version of Xchange. Android to me is the only valid reason for such extreme backward compatibility as Java 8 and as @timmolter stated this library in its current form can run on Android while leveraging newer APIs.

**Comment by timmolter** [comment] 2021-06-21 07:35
"but it will always break in runtime when a method from Java 9 API or above is used and the underneath JRE does not support them" 
This is the problem that I didn't even know existed until recently. I thought that compiling Java 11 code to be Java 8 compatible would be ok, but it's not always the case. So now, we have a situation where XChange really isn't 100% Java8/Android compatible and it's being held back be the Android constraint from going 100% to Java 11. It's now not satisfying either end.

**Comment by mrmx** [comment] 2021-07-10 15:12
I'm in for having jdk8 support, at this moment there are no such big differences (like this simple bug) to not have a Java 8 CI build available. I'm using the lib on a server with other components that are java8 battle tested and also the android code base support is enough to have it. At least for a while more and then please update the docs poms etc.. for developers to be aware of this req.

**Comment by mrmx** [comment] 2021-07-10 15:13
I'm also available for fix all bugs like this one to keep this compatibility until it's not needed anymore.

**Closed** 2021-07-22 13:32 UTC
