### ISSUE TITLE
[35 mBTC Bounty] Implement Bit-Z

### ISSUE THREAD

**Issue by cymp** [knowm/XChange#2049] opened 2017-12-26 19:53 UTC
Hello,

I am paying a 35mBTC bounty to whomever fully implements the [Bit-Z api](https://www.bit-z.com/api.html) before January 7th. 25mBTC otherwise.

Thanks.

**Comment by Unbr8kbal** [comment] 2018-01-03 06:26
Will start looking at it now.

**Comment by cymp** [comment] 2018-01-04 14:51
@Unbr8kbal Thank you!

**Comment by Flemingjp** [comment] 2018-01-04 21:02
I've made some progress with implementing the API shown at this [pull request](https://github.com/timmolter/XChange/pull/2109)

**Comment by cymp** [comment] 2018-01-05 09:56
@Flemingjp Thank you, I will start to test it when you are finished with the trade implementation.
@Unbr8kbal If you already started the implementation, please synchronize your work with @Flemingjp so that I can split the bounty as fairly as possible if needed.

**Comment by Unbr8kbal** [comment] 2018-01-05 11:13
@Flemingjp fair enough way to jump in there, alright i've almost finished, i was about to sync up, but i've noticed you haven't implement every exchange call... The bitz exchange should look like this: `
  @GET
  @Path("/ticker")
  BitzTickerResponse getTicker(@QueryParam("coin") String pair) throws IOException;

  @GET
  @Path("/depth")
  BitzOrderBookResponse getOrderBook(@QueryParam("coin") String pair) throws IOException;

  @GET
  @Path("/orders")
  BitzOrdersResponse getOrders(@QueryParam("coin") String pair) throws IOException;

  @GET
  @Path("/tickerall")
  BitzTickerResponse getTickerAll(@QueryParam("market") String market) throws IOException;

  @GET
  @Path("/kline")
  BitzTickerResponse getKline(@QueryParam("market") String market) throws IOException;

  @GET
  @Path("/tradeAdd")
  BitzTickerResponse getTradeAdd(@QueryParam("market") String market) throws IOException;

  @GET
  @Path("/openOrders")
  BitzTickerResponse getOpenOrders(@QueryParam("market") String market) throws IOException;

  @GET
  @Path("/tradeCancel")
  BitzTickerResponse getTradeCancel(@QueryParam("market") String market) throws IOException;`

I can merge up mine if you wanna split the bounty.

**Comment by Flemingjp** [comment] 2018-01-05 11:20
@Unbr8kbal Yeah I've only implemented the calls that have a fully developed back end. My current work is filling out the trade calls and authentication. Can merge to whatever extent you see fit, happy to split.

Can you explain the "market" query parameter on the later calls. It isn't documented on the exchanges API.

**Comment by Unbr8kbal** [comment] 2018-01-05 11:28
@Flemingjp All those api's have fully developed backends, i'm not sure sure what you saying. I get it you developed the api that do stuff, those other calls are just look up's, is that what your saying? Like i'll pull it, give me 24 hours going to sleep.

**Comment by Flemingjp** [comment] 2018-01-05 11:38
@Unbr8kbal  I mean the POST methods of the API take several parameters. I assume you've rolled them into one parameter from your example. How far is your implementation? I'll push my remaining work and depending on your progress leave it there

**Comment by Flemingjp** [comment] 2018-01-05 11:51
@Unbr8kbal Oh I see. I've implemented the other endpoints, I just have to push the changes to expose them. This includes ticketAll, kline etc correct?

**Comment by Unbr8kbal** [comment] 2018-01-07 02:12
yeah if you've done them, then push them.

**Comment by Flemingjp** [comment] 2018-01-07 02:15
@Unbr8kbal
I've pushed all my code. Had issues with signing my post requests so I tidied up the code to make it more readable in the hope you've cracked it

**Comment by cymp** [comment] 2018-01-09 16:30
@Unbr8kbal @Flemingjp 
Have you finished ? I would like to start to test as soon as everything is finished.

**Comment by Flemingjp** [comment] 2018-01-09 16:36
@cymp I've contacted the exchange after having some implementation difficulties, they've explained that the API, especially the trade service, is not yet fully operational and hence the problems i've experienced as of late. I'm currently adding in the implementations for when their API is complete. Will push updates soon as possible. I assume @Unbr8kbal  may have had the same issues

**Comment by Flemingjp** [comment] 2018-01-09 16:52
@cymp If you fork my repo you can test some of the market services that I have implemented now if you want to get started. My latest [commit ](https://github.com/Flemingjp/XChange/commit/8be7de323cf5b0e4577ece2a1a30b238e34d049c) supports all market services

**Comment by cymp** [comment] 2018-01-09 16:52
Could you please share more details about what is not operational on their side?

**Comment by Flemingjp** [comment] 2018-01-09 17:01
@cymp They currently haven't finished their trade service, no request is properly dealt with on their end apparently. Apologies it'd taken a while to realise, their customer service is really bad.

**Comment by Flemingjp** [comment] 2018-01-09 17:01
@cymp They currently haven't finished their trade service, no request is properly dealt with on their end apparently. Apologies it'd taken a while to realise, their customer service is really bad.

**Comment by Flemingjp** [comment] 2018-01-09 17:01
@cymp They currently haven't finished their trade service, no request is properly dealt with on their end apparently. Apologies it'd taken a while to realise, their customer service is really bad.

**Comment by Flemingjp** [comment] 2018-01-09 17:01
@cymp They currently haven't finished their trade service, no request is properly dealt with on their end apparently. Apologies it'd taken a while to realise, their customer service is really bad.

**Comment by Flemingjp** [comment] 2018-01-10 14:34
@cymp I've implemented the exchange as far as possible given its current state. The implementation can be taken from my fork. It won't be possible to get a working Trade Service until they implement it fully on their side. @timmolter I've implemented the structures and code I anticipate required to finish the implementation when possible, I'm not sure whether it is appropriate to have a pull request however, what are your thoughts?

**Comment by Flemingjp** [comment] 2018-01-12 11:39
@cymp Have you tested my work?

**Comment by cymp** [comment] 2018-01-12 15:26
@Flemingjp not yet sorry, I would like to only test what is on XChange develop branch, since they are subject to be merged.

**Comment by cymp** [comment] 2018-01-13 22:18
No progress here, I am not working on any implementation atm. 
@Flemingjp  @Unbr8kbal I can pay you half the bounty each for your work, please tell me if it looks fair to share 50/50 between the two of you. I will pay you the remaining of the bounty as soon as bit-z finish their trade api implementation and you implement it. Please tell me if it looks good on your side.

**Comment by Flemingjp** [comment] 2018-01-13 22:29
@cymp I'm still waiting to see any work of @Unbr8kbal I'm afraid

**Comment by cymp** [comment] 2018-01-13 22:31
ok, let's wait for him to reply.

**Comment by Unbr8kbal** [comment] 2018-01-21 05:02
Guys, sorry had family emergency, will pull and review now. I'm fine with NOT splitting the bounty since @Flemingjp really did everything i did but did it faster then me,

**Comment by Flemingjp** [comment] 2018-01-30 11:33
@cymp

**Comment by cymp** [comment] 2018-02-06 20:21
@Flemingjp any news regarding the trade service? I have no use of the library if the trade api is not in service. I also would like to give you a part of the bounties for your work on Bit-Z and Coinegg. Could you provide me a BTC address?

**Comment by Flemingjp** [comment] 2018-02-06 20:26
I've heard no news. However they confirmed I'm on a mailing list for future updates so I'll keep posted. I'll get back to you with a suitable BTC address

**Comment by Flemingjp** [comment] 2018-02-07 16:45
@cymp BTC Address: 1DxzCP6fKx4E9d3mujZLdicgD1d5DFtKQG

**Comment by Flemingjp** [comment] 2018-02-07 16:47
@cymp BTC Address: 1DxzCP6fKx4E9d3mujZLdicgD1d5DFtKQG

**Comment by cymp** [comment] 2018-02-07 16:52
@Flemingjp Ok I am paying you 40 mBTC for your global work on Coinegg and Bit-Z since they both are partially finished/working/usable and since I had/have to work on them. I'm not blaming you though, thank you for your work. Money is on its way!

**Comment by Flemingjp** [comment] 2018-02-07 17:05
@cymp Perfect! I think that is fair. I've enjoyed working on these exchanges despite the challenges. Apologies again, my university term started off pretty busy so my commitment fell away. I'll continue to contribute to these exchanges to get them to a more polished standard when I have the time

**Comment by cymp** [comment] 2018-02-07 17:07
@Flemingjp Great thanks!

**Comment by earce** [comment] 2020-11-09 22:01
Can we close this ticket?

**Closed** 2020-11-10 08:25 UTC
Labels: Bounty, New Exchange
