### ISSUE TITLE
Binance TickSize & LotSize scale issue

### ISSUE THREAD

**Issue by GazitGu** [knowm/XChange#2663] opened 2018-06-20 11:05 UTC
We found that for Biance API, the TickSize and LotSize in reference data may like this:

{
  "timezone": "UTC",
  "serverTime": 1508631584636,
  "rateLimits": [{
      "rateLimitType": "REQUESTS",
      "interval": "MINUTE",
      "limit": 1200
    },
    {
      "rateLimitType": "ORDERS",
      "interval": "SECOND",
      "limit": 10
    },
    {
      "rateLimitType": "ORDERS",
      "interval": "DAY",
      "limit": 100000
    }
  ],
  "exchangeFilters": [],
  "symbols": [{
    "symbol": "ETHBTC",
    "status": "TRADING",
    "baseAsset": "ETH",
    "baseAssetPrecision": 8,
    "quoteAsset": "BTC",
    "quotePrecision": 8,
    "orderTypes": ["LIMIT", "MARKET"],
    "icebergAllowed": false,
    "filters": [{
      "filterType": "PRICE_FILTER",
      "minPrice": "0.00000100",
      "maxPrice": "100000.00000000",
      "tickSize": "0.00000100"
    }, {
      "filterType": "LOT_SIZE",
      "minQty": "0.00100000",
      "maxQty": "100000.00000000",
      "stepSize": "0.00100000"
    }, {
      "filterType": "MIN_NOTIONAL",
      "minNotional": "0.00100000"
    }]
  }]
}
The price scale should be 6 while tick size should be 0.001, From BinanceExhcange.java(line 107-104), it think the whole text as scale, i suggest Using apache common lang3 StringUtils to strip end 0:

for (Filter filter : symbol.getFilters()) { // replace with the new values where available.
          switch (filter.getFilterType()) {
            case "PRICE_FILTER":
              priceScale = numberOfDecimals(filter.getTickSize());
              break;
            case "LOT_SIZE":
              minAmount = new BigDecimal(StringUtils.stripEnd(filter.getMinQty(), "0"));
              maxAmount = new BigDecimal(StringUtils.stripEnd(filter.getMaxQty(), "0"));
              break;
            case "MIN_NOTIONAL":
              minNotional = new BigDecimal(StringUtils.stripEnd(filter.getMinNotional(), "0"));
              break;
          }
        }

This is very useful when check price and quantity before send order out.

Thanks again for your work!

Gazit

**Comment by mgrzaslewicz** [comment] 2018-07-10 20:20
After applying this change priceScale is valid
BinanceExchange.java:106
`priceScale = new BigDecimal(filter.getTickSize()).stripTrailingZeros().scale();`

**Comment by roeiba** [comment] 2018-07-27 09:03
Seems like a duplicate of #2698

**Comment by badgerwithagun** [comment] 2018-11-27 21:33
Fixed by #2870

**Closed** 2019-12-18 10:45 UTC
