### ISSUE TITLE
Bitfinex init exception 

### ISSUE THREAD

**Issue by IhorBr** [knowm/XChange#4021] opened 2021-04-21 20:46 UTC
Caused by: java.lang.IllegalStateException: Duplicate key DOGE/USD (attempted merging values 0.094716 and 0.30776)
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.knowm.xchange.bitfinex.BitfinexExchange.remoteInit(BitfinexExchange.java:85)
        at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:113)
        at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:80)
        at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:38)

**Comment by cyrus13** [comment] 2021-04-21 20:58
This is because Bitfinex added DOGE/USD and it also has a pair: XDC/USD which appears to be a different coin (https://coinmarketcap.com/currencies/xinfin-network/).

The problem is in this part of code in Currency.java:

`  public static final Currency DOGE = createCurrency("DOGE", "Dogecoin", null, "XDC", "XDG");`

that maps both DOGEUSD and XDCUSD to the same pair.

Apparently XDCUSD is the DOGEUSD pair for Kraken. So, it appears that we need to make a different mapping for Bitfinex. Question to the dev team: Have you come across a similar problem in another exchange so that we can follow the same solution?

**Comment by IhorBr** [comment] 2021-04-21 21:17
Thanks for the answer.
other exchanges are working fine( CoinbasePro,Binance,Bitstamp,Exmo,Kraken). Only Bitfinex has a problem

**Comment by mathvdh** [comment] 2021-04-22 07:36
Having the same problem here ... I'm not sure how I can help with solving it .. ?

**Comment by mathvdh** [comment] 2021-04-22 12:13
From my current investigation, @cyrus13  is right and it's a problem of confusion between Doge (DOGE) and XinFin Network (XDC). Because Kraken used to call DOGE XDC But apparently now it's XDG !

Fixing 2 lines in Currency.java so that XDC becomes XinFin and only DOGE and XDG points to doge fixed it for me.

I will submit PR.

**Comment by mathvdh** [comment] 2021-04-22 12:23
I've submited a PR with the fix [here](https://github.com/knowm/XChange/pull/4023)

**Comment by BePe2** [comment] 2021-04-22 14:50
A workaround may be the following (If you create the BitfinexExchange-instance in a similar way):

**spec.setShouldLoadRemoteMetaData(false);**
e = ExchangeFactory.INSTANCE.createExchange(spec);

**Comment by earce** [comment] 2021-04-23 17:37
Closing as fixed in merged review

**Closed by earce** 2021-04-23 17:37 UTC
